rm ~/.bashrc 
rm ~/.gitconfig 
rm ~/.gitignore_global 
rm ~/.pdbrc 
rm ~/.pdbrc.py 
rm ~/.tmux.conf 
rm ~/.toprc 
rm ~/.vimrc 
rm ~/.ssh 
rm ~/.inputrc 
rm ~/.nvtop.sh 
rm ~/.zshrc
rm ~/.bash_profile
